#include "aether_vulkan.h"
#include "generated/shaders_spv.h"
#include <android/native_window.h>
#include <android/log.h>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <vector>
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,"Aether3D",__VA_ARGS__)
namespace {
struct M { float v[16]{}; };
M I(){M r{};r.v[0]=r.v[5]=r.v[10]=r.v[15]=1;return r;}
M mul(const M&a,const M&b){M r{};for(int c=0;c<4;c++)for(int y=0;y<4;y++)for(int k=0;k<4;k++)r.v[c*4+y]+=a.v[k*4+y]*b.v[c*4+k];return r;}
M persp(float f,float a,float n,float z){M r{};float q=1/std::tan(f*.5f);r.v[0]=q/a;r.v[5]=q;r.v[10]=z/(n-z);r.v[11]=-1;r.v[14]=z*n/(n-z);return r;}
M ortho(float l,float r,float b,float t,float n,float f){M m=I();m.v[0]=2/(r-l);m.v[5]=2/(t-b);m.v[10]=1/(n-f);m.v[12]=-(r+l)/(r-l);m.v[13]=-(t+b)/(t-b);m.v[14]=n/(n-f);return m;}
M look(float ex,float ey,float ez,float cx,float cy,float cz){
 float fx=cx-ex,fy=cy-ey,fz=cz-ez,l=std::sqrt(fx*fx+fy*fy+fz*fz);fx/=l;fy/=l;fz/=l;
 float rx=fy,ry=-fx,rz=0,l2=std::sqrt(rx*rx+ry*ry);if(l2<.001f){rx=1;ry=0;rz=0;l2=1;}rx/=l2;ry/=l2;
 float ux=ry*fz,uy=rz*fx-rx*fz,uz=rx*fy-ry*fx;M r=I();
 r.v[0]=rx;r.v[1]=ux;r.v[2]=-fx;r.v[4]=ry;r.v[5]=uy;r.v[6]=-fy;r.v[8]=rz;r.v[9]=uz;r.v[10]=-fz;
 r.v[12]=-(rx*ex+ry*ey+rz*ez);r.v[13]=-(ux*ex+uy*ey+uz*ez);r.v[14]=fx*ex+fy*ey+fz*ez;return r;
}
VkShaderModule shader(VkDevice d,const uint32_t*p,size_t n){VkShaderModuleCreateInfo i{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};i.codeSize=n*4;i.pCode=p;VkShaderModule m{};return vkCreateShaderModule(d,&i,nullptr,&m)==VK_SUCCESS?m:VK_NULL_HANDLE;}
}
namespace aether {
VulkanRenderer::VulkanRenderer(){init();}
VulkanRenderer::~VulkanRenderer(){shutdown();}
uint32_t VulkanRenderer::find_memory(uint32_t bits,VkMemoryPropertyFlags f)const{VkPhysicalDeviceMemoryProperties p{};vkGetPhysicalDeviceMemoryProperties(gpu_,&p);for(uint32_t i=0;i<p.memoryTypeCount;i++)if((bits&(1u<<i))&&(p.memoryTypes[i].propertyFlags&f)==f)return i;return UINT32_MAX;}
bool VulkanRenderer::create_buffer(VkDeviceSize s,VkBufferUsageFlags u,VkMemoryPropertyFlags p,VkBuffer&b,VkDeviceMemory&m){VkBufferCreateInfo i{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};i.size=s;i.usage=u;i.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(vkCreateBuffer(device_,&i,nullptr,&b)!=VK_SUCCESS)return false;VkMemoryRequirements q{};vkGetBufferMemoryRequirements(device_,b,&q);uint32_t t=find_memory(q.memoryTypeBits,p);if(t==UINT32_MAX)return false;VkMemoryAllocateInfo a{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};a.allocationSize=q.size;a.memoryTypeIndex=t;if(vkAllocateMemory(device_,&a,nullptr,&m)!=VK_SUCCESS)return false;return vkBindBufferMemory(device_,b,m,0)==VK_SUCCESS;}
bool VulkanRenderer::create_image(VkFormat f,VkImageUsageFlags u,VkImage&i,VkDeviceMemory&m,VkImageView&v){VkImageCreateInfo c{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};c.imageType=VK_IMAGE_TYPE_2D;c.format=f;c.extent={extent_.width,extent_.height,1};c.mipLevels=1;c.arrayLayers=1;c.samples=VK_SAMPLE_COUNT_1_BIT;c.tiling=VK_IMAGE_TILING_OPTIMAL;c.usage=u;if(vkCreateImage(device_,&c,nullptr,&i)!=VK_SUCCESS)return false;VkMemoryRequirements q{};vkGetImageMemoryRequirements(device_,i,&q);uint32_t t=find_memory(q.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);if(t==UINT32_MAX)return false;VkMemoryAllocateInfo a{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};a.allocationSize=q.size;a.memoryTypeIndex=t;if(vkAllocateMemory(device_,&a,nullptr,&m)!=VK_SUCCESS)return false;vkBindImageMemory(device_,i,m,0);VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=i;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=f;vi.subresourceRange={VK_IMAGE_ASPECT_DEPTH_BIT,0,1,0,1};return vkCreateImageView(device_,&vi,nullptr,&v)==VK_SUCCESS;}
bool VulkanRenderer::create_instance(){VkApplicationInfo a{VK_STRUCTURE_TYPE_APPLICATION_INFO};a.pApplicationName="Aether 3D";a.applicationVersion=VK_MAKE_VERSION(0,2,0);a.pEngineName="Aether Engine";a.engineVersion=VK_MAKE_VERSION(0,2,0);a.apiVersion=VK_API_VERSION_1_1;const char*e[]={"VK_KHR_surface","VK_KHR_android_surface"};VkInstanceCreateInfo c{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};c.pApplicationInfo=&a;c.enabledExtensionCount=2;c.ppEnabledExtensionNames=e;return vkCreateInstance(&c,nullptr,&instance_)==VK_SUCCESS;}
bool VulkanRenderer::create_device(){uint32_t n=0;vkEnumeratePhysicalDevices(instance_,&n,nullptr);if(!n)return false;std::vector<VkPhysicalDevice>d(n);vkEnumeratePhysicalDevices(instance_,&n,d.data());for(auto x:d){uint32_t qn=0;vkGetPhysicalDeviceQueueFamilyProperties(x,&qn,nullptr);std::vector<VkQueueFamilyProperties>q(qn);vkGetPhysicalDeviceQueueFamilyProperties(x,&qn,q.data());for(uint32_t i=0;i<qn;i++){VkBool32 p=0;vkGetPhysicalDeviceSurfaceSupportKHR(x,i,surface_,&p);if((q[i].queueFlags&VK_QUEUE_GRAPHICS_BIT)&&p){gpu_=x;queue_family_=i;float pr=1;VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qi.queueFamilyIndex=i;qi.queueCount=1;qi.pQueuePriorities=&pr;const char*e[]={"VK_KHR_swapchain"};VkDeviceCreateInfo ci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};ci.queueCreateInfoCount=1;ci.pQueueCreateInfos=&qi;ci.enabledExtensionCount=1;ci.ppEnabledExtensionNames=e;if(vkCreateDevice(gpu_,&ci,nullptr,&device_)!=VK_SUCCESS)return false;vkGetDeviceQueue(device_,i,0,&graphics_queue_);return true;}}}return false;}
bool VulkanRenderer::create_surface(){if(!window_)return false;VkAndroidSurfaceCreateInfoKHR c{VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR};c.window=window_;return vkCreateAndroidSurfaceKHR(instance_,&c,nullptr,&surface_)==VK_SUCCESS;}
bool VulkanRenderer::create_swapchain(){VkSurfaceCapabilitiesKHR c{};if(vkGetPhysicalDeviceSurfaceCapabilitiesKHR(gpu_,surface_,&c)!=VK_SUCCESS)return false;uint32_t n=0;vkGetPhysicalDeviceSurfaceFormatsKHR(gpu_,surface_,&n,nullptr);if(!n)return false;std::vector<VkSurfaceFormatKHR>f(n);vkGetPhysicalDeviceSurfaceFormatsKHR(gpu_,surface_,&n,f.data());VkSurfaceFormatKHR fmt=f[0];for(auto x:f)if(x.format==VK_FORMAT_R8G8B8A8_UNORM||x.format==VK_FORMAT_B8G8R8A8_UNORM){fmt=x;break;}swapchain_format_=fmt.format;VkExtent2D e=c.currentExtent;if(e.width==UINT32_MAX){e.width=std::clamp(width_,c.minImageExtent.width,c.maxImageExtent.width);e.height=std::clamp(height_,c.minImageExtent.height,c.maxImageExtent.height);}extent_=e;width_=e.width;height_=e.height;uint32_t count=std::max(2u,c.minImageCount);if(c.maxImageCount)count=std::min(count,c.maxImageCount);VkSwapchainCreateInfoKHR i{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};i.surface=surface_;i.minImageCount=count;i.imageFormat=fmt.format;i.imageColorSpace=fmt.colorSpace;i.imageExtent=e;i.imageArrayLayers=1;i.imageUsage=VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;i.imageSharingMode=VK_SHARING_MODE_EXCLUSIVE;i.preTransform=c.currentTransform;i.compositeAlpha=VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;i.presentMode=VK_PRESENT_MODE_FIFO_KHR;i.clipped=VK_TRUE;if(vkCreateSwapchainKHR(device_,&i,nullptr,&swapchain_)!=VK_SUCCESS)return false;vkGetSwapchainImagesKHR(device_,swapchain_,&n,nullptr);swapchain_images_.resize(n);vkGetSwapchainImagesKHR(device_,swapchain_,&n,swapchain_images_.data());swapchain_views_.resize(n);for(uint32_t k=0;k<n;k++){VkImageViewCreateInfo v{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};v.image=swapchain_images_[k];v.viewType=VK_IMAGE_VIEW_TYPE_2D;v.format=swapchain_format_;v.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};if(vkCreateImageView(device_,&v,nullptr,&swapchain_views_[k])!=VK_SUCCESS)return false;}return true;}
bool VulkanRenderer::create_render_targets(){VkFormat candidates[]={VK_FORMAT_D32_SFLOAT,VK_FORMAT_D16_UNORM};depth_format_=VK_FORMAT_UNDEFINED;for(VkFormat f:candidates){VkFormatProperties p{};vkGetPhysicalDeviceFormatProperties(gpu_,f,&p);if(p.optimalTilingFeatures&VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT){depth_format_=f;break;}}if(depth_format_==VK_FORMAT_UNDEFINED)return false;VkAttachmentDescription a[2]{};a[0].format=swapchain_format_;a[0].samples=VK_SAMPLE_COUNT_1_BIT;a[0].loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;a[0].storeOp=VK_ATTACHMENT_STORE_OP_STORE;a[0].finalLayout=VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;a[1].format=depth_format_;a[1].samples=VK_SAMPLE_COUNT_1_BIT;a[1].loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;a[1].storeOp=VK_ATTACHMENT_STORE_OP_DONT_CARE;a[1].finalLayout=VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;VkAttachmentReference c{0,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL},d{1,VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};VkSubpassDescription s{};s.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;s.colorAttachmentCount=1;s.pColorAttachments=&c;s.pDepthStencilAttachment=&d;VkRenderPassCreateInfo r{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};r.attachmentCount=2;r.pAttachments=a;r.subpassCount=1;r.pSubpasses=&s;if(vkCreateRenderPass(device_,&r,nullptr,&render_pass_)!=VK_SUCCESS)return false;if(!create_image(depth_format_,VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,depth_image_,depth_memory_,depth_view_))return false;framebuffers_.resize(swapchain_views_.size());for(size_t k=0;k<framebuffers_.size();k++){VkImageView at[]={swapchain_views_[k],depth_view_};VkFramebufferCreateInfo x{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};x.renderPass=render_pass_;x.attachmentCount=2;x.pAttachments=at;x.width=extent_.width;x.height=extent_.height;x.layers=1;if(vkCreateFramebuffer(device_,&x,nullptr,&framebuffers_[k])!=VK_SUCCESS)return false;}return true;}
bool VulkanRenderer::create_mesh(){
 static const VulkanRenderer::Vertex v[]={
 {-1,-1,-1,0,0,-1,.18,.65,1},{1,-1,-1,0,0,-1,.18,.65,1},{1,1,-1,0,0,-1,.18,.65,1},{-1,1,-1,0,0,-1,.18,.65,1},
 {-1,-1,1,0,0,1,1,.35,.2},{1,-1,1,0,0,1,1,.35,.2},{1,1,1,0,0,1,1,.35,.2},{-1,1,1,0,0,1,1,.35,.2},
 {-1,-1,-1,-1,0,0,.2,1,.45},{-1,1,-1,-1,0,0,.2,1,.45},{-1,1,1,-1,0,0,.2,1,.45},{-1,-1,1,-1,0,0,.2,1,.45},
 {1,-1,-1,1,0,0,1,.25,.75},{1,-1,1,1,0,0,1,.25,.75},{1,1,1,1,0,0,1,.25,.75},{1,1,-1,1,0,0,1,.25,.75},
 {-1,-1,-1,0,-1,0,.85,.2,.85},{-1,-1,1,0,-1,0,.85,.2,.85},{1,-1,1,0,-1,0,.85,.2,.85},{1,-1,-1,0,-1,0,.85,.2,.85},
 {-1,1,-1,0,1,0,.95,.85,.2},{1,1,-1,0,1,0,.95,.85,.2},{1,1,1,0,1,0,.95,.85,.2},{-1,1,1,0,1,0,.95,.85,.2},
 {-14,-1.05,-14,0,1,0,.12,.16,.20},{14,-1.05,-14,0,1,0,.12,.16,.20},{14,-1.05,14,0,1,0,.12,.16,.20},{-14,-1.05,14,0,1,0,.12,.16,.20}};
 static const uint16_t ix[]={0,1,2,2,3,0,4,6,5,6,4,7,8,9,10,10,11,8,12,13,14,14,15,12,16,17,18,18,19,16,20,22,21,22,20,23,24,25,26,26,27,24};
 index_count_=42;
 if(!create_buffer(sizeof(v),VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,vertex_buffer_,vertex_memory_)||!create_buffer(sizeof(ix),VK_BUFFER_USAGE_INDEX_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,index_buffer_,index_memory_))return false;
 void*p=nullptr;vkMapMemory(device_,vertex_memory_,0,sizeof(v),0,&p);std::memcpy(p,v,sizeof(v));vkUnmapMemory(device_,vertex_memory_);vkMapMemory(device_,index_memory_,0,sizeof(ix),0,&p);std::memcpy(p,ix,sizeof(ix));vkUnmapMemory(device_,index_memory_);return true;
}
bool VulkanRenderer::create_descriptors(){
 VkDescriptorSetLayoutBinding c{0,VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,1,VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT|VK_SHADER_STAGE_COMPUTE_BIT,nullptr};VkDescriptorSetLayoutCreateInfo ci{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};ci.bindingCount=1;ci.pBindings=&c;if(vkCreateDescriptorSetLayout(device_,&ci,nullptr,&camera_set_layout_)!=VK_SUCCESS)return false;
 VkDescriptorSetLayoutBinding l[3]={{0,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,1,VK_SHADER_STAGE_FRAGMENT_BIT|VK_SHADER_STAGE_COMPUTE_BIT,nullptr},{1,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,1,VK_SHADER_STAGE_FRAGMENT_BIT|VK_SHADER_STAGE_COMPUTE_BIT,nullptr},{2,VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,1,VK_SHADER_STAGE_FRAGMENT_BIT,nullptr}};VkDescriptorSetLayoutCreateInfo li{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};li.bindingCount=3;li.pBindings=l;if(vkCreateDescriptorSetLayout(device_,&li,nullptr,&lighting_set_layout_)!=VK_SUCCESS)return false;
 VkDescriptorPoolSize ps[]={{VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,1},{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,2},{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,1}};VkDescriptorPoolCreateInfo pi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};pi.maxSets=2;pi.poolSizeCount=3;pi.pPoolSizes=ps;if(vkCreateDescriptorPool(device_,&pi,nullptr,&descriptor_pool_)!=VK_SUCCESS)return false;
 VkDescriptorSetLayout ls[]={camera_set_layout_,lighting_set_layout_};VkDescriptorSet ss[2]{};VkDescriptorSetAllocateInfo ai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};ai.descriptorPool=descriptor_pool_;ai.descriptorSetCount=2;ai.pSetLayouts=ls;if(vkAllocateDescriptorSets(device_,&ai,ss)!=VK_SUCCESS)return false;camera_set_=ss[0];lighting_set_=ss[1];
 VkDescriptorBufferInfo cb{camera_buffer_,0,sizeof(CameraData)},lb{light_buffer_,0,sizeof(LightData)},xb{cluster_buffer_,0,VK_WHOLE_SIZE};VkDescriptorImageInfo si{shadow_sampler_,shadow_view_,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};VkWriteDescriptorSet w[4]{};for(auto&x:w)x.sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
 w[0].dstSet=camera_set_;w[0].dstBinding=0;w[0].descriptorType=VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;w[0].descriptorCount=1;w[0].pBufferInfo=&cb;
 w[1].dstSet=lighting_set_;w[1].dstBinding=0;w[1].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;w[1].descriptorCount=1;w[1].pBufferInfo=&lb;
 w[2].dstSet=lighting_set_;w[2].dstBinding=1;w[2].descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;w[2].descriptorCount=1;w[2].pBufferInfo=&xb;
 w[3].dstSet=lighting_set_;w[3].dstBinding=2;w[3].descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;w[3].descriptorCount=1;w[3].pImageInfo=&si;vkUpdateDescriptorSets(device_,4,w,0,nullptr);return true;
}
bool VulkanRenderer::create_pipelines(){
 VkDescriptorSetLayout ls[]={camera_set_layout_,lighting_set_layout_};VkPushConstantRange pcr{VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,4};VkPipelineLayoutCreateInfo pl{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pl.setLayoutCount=2;pl.pSetLayouts=ls;pl.pushConstantRangeCount=1;pl.pPushConstantRanges=&pcr;if(vkCreatePipelineLayout(device_,&pl,nullptr,&pipeline_layout_)!=VK_SUCCESS)return false;
 VkShaderModule vs=shader(device_,aether_shader_spv::vert,aether_shader_spv::vert_words),fs=shader(device_,aether_shader_spv::frag,aether_shader_spv::frag_words),cs=shader(device_,aether_shader_spv::comp,aether_shader_spv::comp_words);if(!vs||!fs||!cs)return false;
 VkPipelineShaderStageCreateInfo st[2]{};for(auto&x:st)x.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;st[0].stage=VK_SHADER_STAGE_VERTEX_BIT;st[0].module=vs;st[0].pName="main";st[1].stage=VK_SHADER_STAGE_FRAGMENT_BIT;st[1].module=fs;st[1].pName="main";
 VkVertexInputBindingDescription b{0,sizeof(Vertex),VK_VERTEX_INPUT_RATE_VERTEX};VkVertexInputAttributeDescription at[]={{0,0,VK_FORMAT_R32G32B32_SFLOAT,0},{1,0,VK_FORMAT_R32G32B32_SFLOAT,12},{2,0,VK_FORMAT_R32G32B32_SFLOAT,24}};VkPipelineVertexInputStateCreateInfo vi{VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};vi.vertexBindingDescriptionCount=1;vi.pVertexBindingDescriptions=&b;vi.vertexAttributeDescriptionCount=3;vi.pVertexAttributeDescriptions=at;
 VkPipelineInputAssemblyStateCreateInfo ia{VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};ia.topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;VkViewport vp{0,0,(float)extent_.width,(float)extent_.height,0,1};VkRect2D sc{{0,0},extent_};VkPipelineViewportStateCreateInfo vv{VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};vv.viewportCount=1;vv.pViewports=&vp;vv.scissorCount=1;vv.pScissors=&sc;
 VkPipelineRasterizationStateCreateInfo rs{VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};rs.polygonMode=VK_POLYGON_MODE_FILL;rs.cullMode=VK_CULL_MODE_BACK_BIT;rs.frontFace=VK_FRONT_FACE_COUNTER_CLOCKWISE;rs.lineWidth=1;VkPipelineMultisampleStateCreateInfo ms{VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};ms.rasterizationSamples=VK_SAMPLE_COUNT_1_BIT;VkPipelineDepthStencilStateCreateInfo ds{VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO};ds.depthTestEnable=VK_TRUE;ds.depthWriteEnable=VK_TRUE;ds.depthCompareOp=VK_COMPARE_OP_LESS;VkPipelineColorBlendAttachmentState ba{};ba.colorWriteMask=0xF;VkPipelineColorBlendStateCreateInfo bc{VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};bc.attachmentCount=1;bc.pAttachments=&ba;
 VkGraphicsPipelineCreateInfo gp{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};gp.stageCount=2;gp.pStages=st;gp.pVertexInputState=&vi;gp.pInputAssemblyState=&ia;gp.pViewportState=&vv;gp.pRasterizationState=&rs;gp.pMultisampleState=&ms;gp.pDepthStencilState=&ds;gp.pColorBlendState=&bc;gp.layout=pipeline_layout_;gp.renderPass=render_pass_;if(vkCreateGraphicsPipelines(device_,VK_NULL_HANDLE,1,&gp,nullptr,&graphics_pipeline_)!=VK_SUCCESS)return false;
 VkPipelineRasterizationStateCreateInfo srs=rs;srs.cullMode=VK_CULL_MODE_FRONT_BIT;VkPipelineDepthStencilStateCreateInfo sds=ds;sds.depthTestEnable=VK_FALSE;sds.depthWriteEnable=VK_FALSE;VkGraphicsPipelineCreateInfo sgp=gp;sgp.pRasterizationState=&srs;sgp.pDepthStencilState=&sds;if(vkCreateGraphicsPipelines(device_,VK_NULL_HANDLE,1,&sgp,nullptr,&sky_pipeline_)!=VK_SUCCESS)return false;
 VkPipelineRasterizationStateCreateInfo shrs=rs;shrs.cullMode=VK_CULL_MODE_NONE;shrs.depthBiasEnable=VK_TRUE;shrs.depthBiasConstantFactor=1.5f;shrs.depthBiasSlopeFactor=2.0f;VkPipelineDepthStencilStateCreateInfo shds=ds;shds.depthCompareOp=VK_COMPARE_OP_LESS_OR_EQUAL;VkViewport svp{0,0,1024,1024,0,1};VkRect2D ssc{{0,0},{1024,1024}};VkPipelineViewportStateCreateInfo svv=vv;svv.pViewports=&svp;svv.pScissors=&ssc;VkPipelineShaderStageCreateInfo ss=st[0];VkGraphicsPipelineCreateInfo shp{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};shp.stageCount=1;shp.pStages=&ss;shp.pVertexInputState=&vi;shp.pInputAssemblyState=&ia;shp.pViewportState=&svv;shp.pRasterizationState=&shrs;shp.pMultisampleState=&ms;shp.pDepthStencilState=&shds;shp.layout=pipeline_layout_;shp.renderPass=shadow_render_pass_;if(vkCreateGraphicsPipelines(device_,VK_NULL_HANDLE,1,&shp,nullptr,&shadow_pipeline_)!=VK_SUCCESS)return false;
 VkPipelineShaderStageCreateInfo csx{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO};csx.stage=VK_SHADER_STAGE_COMPUTE_BIT;csx.module=cs;csx.pName="main";VkComputePipelineCreateInfo cp{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};cp.stage=csx;cp.layout=pipeline_layout_;if(vkCreateComputePipelines(device_,VK_NULL_HANDLE,1,&cp,nullptr,&compute_pipeline_)!=VK_SUCCESS)return false;
 vkDestroyShaderModule(device_,vs,nullptr);vkDestroyShaderModule(device_,fs,nullptr);vkDestroyShaderModule(device_,cs,nullptr);return true;
}
bool VulkanRenderer::create_shadow_resources(){
 const uint32_t S=1024;VkImageCreateInfo ic{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};ic.imageType=VK_IMAGE_TYPE_2D;ic.format=VK_FORMAT_D16_UNORM;ic.extent={S,S,1};ic.mipLevels=1;ic.arrayLayers=1;ic.samples=VK_SAMPLE_COUNT_1_BIT;ic.tiling=VK_IMAGE_TILING_OPTIMAL;ic.usage=VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT|VK_IMAGE_USAGE_SAMPLED_BIT;if(vkCreateImage(device_,&ic,nullptr,&shadow_image_)!=VK_SUCCESS)return false;
 VkMemoryRequirements mr{};vkGetImageMemoryRequirements(device_,shadow_image_,&mr);uint32_t mt=find_memory(mr.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);if(mt==UINT32_MAX)return false;VkMemoryAllocateInfo ma{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ma.allocationSize=mr.size;ma.memoryTypeIndex=mt;if(vkAllocateMemory(device_,&ma,nullptr,&shadow_memory_)!=VK_SUCCESS)return false;if(vkBindImageMemory(device_,shadow_image_,shadow_memory_,0)!=VK_SUCCESS)return false;
 VkImageViewCreateInfo iv{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};iv.image=shadow_image_;iv.viewType=VK_IMAGE_VIEW_TYPE_2D;iv.format=VK_FORMAT_D16_UNORM;iv.subresourceRange={VK_IMAGE_ASPECT_DEPTH_BIT,0,1,0,1};if(vkCreateImageView(device_,&iv,nullptr,&shadow_view_)!=VK_SUCCESS)return false;
 VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};si.magFilter=VK_FILTER_LINEAR;si.minFilter=VK_FILTER_LINEAR;si.mipmapMode=VK_SAMPLER_MIPMAP_MODE_NEAREST;si.addressModeU=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER;si.addressModeV=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER;si.addressModeW=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER;si.borderColor=VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE;si.compareEnable=VK_TRUE;si.compareOp=VK_COMPARE_OP_LESS_OR_EQUAL;si.maxLod=0;if(vkCreateSampler(device_,&si,nullptr,&shadow_sampler_)!=VK_SUCCESS)return false;
 VkAttachmentDescription a{};a.format=VK_FORMAT_D16_UNORM;a.samples=VK_SAMPLE_COUNT_1_BIT;a.loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;a.storeOp=VK_ATTACHMENT_STORE_OP_STORE;a.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;a.finalLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;VkAttachmentReference d{0,VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};VkSubpassDescription sp{};sp.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sp.pDepthStencilAttachment=&d;
 VkSubpassDependency dep[2]{};dep[0].srcSubpass=VK_SUBPASS_EXTERNAL;dep[0].dstSubpass=0;dep[0].srcStageMask=VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;dep[0].dstStageMask=VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;dep[0].srcAccessMask=VK_ACCESS_SHADER_READ_BIT;dep[0].dstAccessMask=VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;dep[0].dependencyFlags=VK_DEPENDENCY_BY_REGION_BIT;dep[1].srcSubpass=0;dep[1].dstSubpass=VK_SUBPASS_EXTERNAL;dep[1].srcStageMask=VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;dep[1].dstStageMask=VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;dep[1].srcAccessMask=VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;dep[1].dstAccessMask=VK_ACCESS_SHADER_READ_BIT;dep[1].dependencyFlags=VK_DEPENDENCY_BY_REGION_BIT;
 VkRenderPassCreateInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};rp.attachmentCount=1;rp.pAttachments=&a;rp.subpassCount=1;rp.pSubpasses=&sp;rp.dependencyCount=2;rp.pDependencies=dep;if(vkCreateRenderPass(device_,&rp,nullptr,&shadow_render_pass_)!=VK_SUCCESS)return false;VkImageView at[]={shadow_view_};VkFramebufferCreateInfo fb{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};fb.renderPass=shadow_render_pass_;fb.attachmentCount=1;fb.pAttachments=at;fb.width=S;fb.height=S;fb.layers=1;return vkCreateFramebuffer(device_,&fb,nullptr,&shadow_framebuffer_)==VK_SUCCESS;
}
bool VulkanRenderer::create_forward_plus_resources(){
 VkCommandPoolCreateInfo p{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};p.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;p.queueFamilyIndex=queue_family_;if(vkCreateCommandPool(device_,&p,nullptr,&command_pool_)!=VK_SUCCESS)return false;VkCommandBufferAllocateInfo a{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};a.commandPool=command_pool_;a.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;a.commandBufferCount=1;if(vkAllocateCommandBuffers(device_,&a,&command_buffer_)!=VK_SUCCESS)return false;VkSemaphoreCreateInfo si{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};if(vkCreateSemaphore(device_,&si,nullptr,&image_available_)!=VK_SUCCESS||vkCreateSemaphore(device_,&si,nullptr,&render_finished_)!=VK_SUCCESS)return false;VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};fi.flags=VK_FENCE_CREATE_SIGNALED_BIT;if(vkCreateFence(device_,&fi,nullptr,&in_flight_)!=VK_SUCCESS)return false;
 if(!create_buffer(sizeof(CameraData),VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,camera_buffer_,camera_memory_))return false;if(!create_buffer(sizeof(LightData),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,light_buffer_,light_memory_))return false;VkDeviceSize cs=VkDeviceSize(16*9*24*5)*sizeof(uint32_t);if(!create_buffer(cs,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,cluster_buffer_,cluster_memory_))return false;
 vkMapMemory(device_,camera_memory_,0,sizeof(CameraData),0,&camera_mapped_);vkMapMemory(device_,light_memory_,0,sizeof(LightData),0,&light_mapped_);vkMapMemory(device_,cluster_memory_,0,cs,0,&cluster_mapped_);std::memset(cluster_mapped_,0,(size_t)cs);
 LightData l{};l.lights[0]={{2.5f,3.2f,2.5f,5.5f},{1,.78f,.48f,2.8f}};l.lights[1]={{-3.5f,1.8f,1,4.5f},{.28f,.55f,1,2.2f}};l.lights[2]={{0,2.2f,-4,4},{1,.25f,.12f,2}};l.lights[3]={{3,.5f,-3,3.2f},{.32f,1,.55f,1.8f}};std::memcpy(light_mapped_,&l,sizeof(l));
 return create_mesh()&&create_shadow_resources()&&create_descriptors()&&create_pipelines();
}
bool VulkanRenderer::init(){if(!create_instance())return false;initialized_=true;return true;}
void VulkanRenderer::set_window(ANativeWindow*w){if(w==window_&&swapchain_)return;if(!w){if(device_)vkDeviceWaitIdle(device_);destroy_swapchain();if(surface_)vkDestroySurfaceKHR(instance_,surface_,nullptr);surface_=VK_NULL_HANDLE;window_=nullptr;return;}if(device_)vkDeviceWaitIdle(device_);destroy_swapchain();window_=w;if(!surface_&&!create_surface()){LOGE("surface creation failed");return;}if(!device_&&!create_device()){LOGE("device creation failed");return;}if(!create_swapchain()||!create_render_targets()||!create_forward_plus_resources()){LOGE("Vulkan 3D resource creation failed");return;}dirty_=false;}
void VulkanRenderer::resize(uint32_t w,uint32_t h){width_=std::max(1u,w);height_=std::max(1u,h);dirty_=true;}
void VulkanRenderer::recreate_swapchain(){if(!device_||!surface_)return;vkDeviceWaitIdle(device_);destroy_swapchain();if(create_swapchain()&&create_render_targets()&&create_forward_plus_resources())dirty_=false;}
void VulkanRenderer::update_camera(){
 float a=extent_.height?float(extent_.width)/float(extent_.height):1;float cp=std::cos(pitch_),sp=std::sin(pitch_),cy=std::cos(yaw_),sy=std::sin(yaw_);float ex=sy*cp*distance_,ey=1.5f+sp*distance_,ez=cy*cp*distance_;M v=look(ex,ey,ez,0,.2f,0),p=persp(1.05f,a,.1f,100),vp=mul(p,v);
 const float sx0=-.45f,sy0=.80f,sz0=-.35f;float sl=std::sqrt(sx0*sx0+sy0*sy0+sz0*sz0),sx=sx0/sl,sy=sy0/sl,sz=sz0/sl;M lv=look(-sx*22,-sy*22,-sz*22,0,0,0),lp=ortho(-10,10,-10,10,.1f,50),lvp=mul(lp,lv);
 CameraData c{};std::memcpy(c.view_proj,vp.v,64);std::memcpy(c.view,v.v,64);c.viewport_near_far[0]=float(extent_.width);c.viewport_near_far[1]=float(extent_.height);c.viewport_near_far[2]=.1f;c.viewport_near_far[3]=100;std::memcpy(c.light_view_proj,lvp.v,64);c.camera_pos_time[0]=ex;c.camera_pos_time[1]=ey;c.camera_pos_time[2]=ez;c.camera_pos_time[3]=time_;c.sun_dir_intensity[0]=sx;c.sun_dir_intensity[1]=sy;c.sun_dir_intensity[2]=sz;c.sun_dir_intensity[3]=3.6f;c.sky_params[0]=.72f;c.sky_params[1]=.018f;c.sky_params[2]=.55f;c.sky_params[3]=0;std::memcpy(camera_mapped_,&c,sizeof(c));
}
void VulkanRenderer::touch(float x,float y,int action){void VulkanRenderer::touch(float x,float y,int action){if(action==0){touching_=true;last_x_=x;last_y_=y;}else if(action==2&&touching_){yaw_-=(x-last_x_)*.008f;pitch_=std::clamp(pitch_-(y-last_y_)*.008f,-1.1f,1.1f);last_x_=x;last_y_=y;}else if(action==1)touching_=false;}
void VulkanRenderer::destroy_swapchain(){
 if(!device_)return;if(in_flight_)vkDestroyFence(device_,in_flight_,nullptr);if(image_available_)vkDestroySemaphore(device_,image_available_,nullptr);if(render_finished_)vkDestroySemaphore(device_,render_finished_,nullptr);in_flight_=VK_NULL_HANDLE;image_available_=render_finished_=VK_NULL_HANDLE;
 if(camera_mapped_)vkUnmapMemory(device_,camera_memory_);if(light_mapped_)vkUnmapMemory(device_,light_memory_);if(cluster_mapped_)vkUnmapMemory(device_,cluster_memory_);camera_mapped_=light_mapped_=cluster_mapped_=nullptr;
 VkBuffer bs[]={camera_buffer_,light_buffer_,cluster_buffer_,vertex_buffer_,index_buffer_};VkDeviceMemory ms[]={camera_memory_,light_memory_,cluster_memory_,vertex_memory_,index_memory_};for(int i=0;i<5;i++){if(bs[i])vkDestroyBuffer(device_,bs[i],nullptr);if(ms[i])vkFreeMemory(device_,ms[i],nullptr);}camera_buffer_=light_buffer_=cluster_buffer_=vertex_buffer_=index_buffer_=VK_NULL_HANDLE;camera_memory_=light_memory_=cluster_memory_=vertex_memory_=index_memory_=VK_NULL_HANDLE;
 if(shadow_sampler_)vkDestroySampler(device_,shadow_sampler_,nullptr);if(shadow_view_)vkDestroyImageView(device_,shadow_view_,nullptr);if(shadow_image_)vkDestroyImage(device_,shadow_image_,nullptr);if(shadow_memory_)vkFreeMemory(device_,shadow_memory_,nullptr);if(shadow_framebuffer_)vkDestroyFramebuffer(device_,shadow_framebuffer_,nullptr);if(shadow_render_pass_)vkDestroyRenderPass(device_,shadow_render_pass_,nullptr);shadow_sampler_=VK_NULL_HANDLE;shadow_view_=VK_NULL_HANDLE;shadow_image_=VK_NULL_HANDLE;shadow_memory_=VK_NULL_HANDLE;shadow_framebuffer_=VK_NULL_HANDLE;shadow_render_pass_=VK_NULL_HANDLE;
 if(depth_view_)vkDestroyImageView(device_,depth_view_,nullptr);if(depth_image_)vkDestroyImage(device_,depth_image_,nullptr);if(depth_memory_)vkFreeMemory(device_,depth_memory_,nullptr);depth_view_=VK_NULL_HANDLE;depth_image_=VK_NULL_HANDLE;depth_memory_=VK_NULL_HANDLE;for(auto f:framebuffers_)vkDestroyFramebuffer(device_,f,nullptr);framebuffers_.clear();
 if(graphics_pipeline_)vkDestroyPipeline(device_,graphics_pipeline_,nullptr);if(sky_pipeline_)vkDestroyPipeline(device_,sky_pipeline_,nullptr);if(shadow_pipeline_)vkDestroyPipeline(device_,shadow_pipeline_,nullptr);if(compute_pipeline_)vkDestroyPipeline(device_,compute_pipeline_,nullptr);if(pipeline_layout_)vkDestroyPipelineLayout(device_,pipeline_layout_,nullptr);graphics_pipeline_=sky_pipeline_=shadow_pipeline_=compute_pipeline_=VK_NULL_HANDLE;pipeline_layout_=VK_NULL_HANDLE;
 if(descriptor_pool_)vkDestroyDescriptorPool(device_,descriptor_pool_,nullptr);if(camera_set_layout_)vkDestroyDescriptorSetLayout(device_,camera_set_layout_,nullptr);if(lighting_set_layout_)vkDestroyDescriptorSetLayout(device_,lighting_set_layout_,nullptr);descriptor_pool_=VK_NULL_HANDLE;camera_set_layout_=lighting_set_layout_=VK_NULL_HANDLE;camera_set_=lighting_set_=VK_NULL_HANDLE;
 if(render_pass_)vkDestroyRenderPass(device_,render_pass_,nullptr);render_pass_=VK_NULL_HANDLE;if(command_pool_)vkDestroyCommandPool(device_,command_pool_,nullptr);command_pool_=VK_NULL_HANDLE;command_buffer_=VK_NULL_HANDLE;for(auto v:swapchain_views_)vkDestroyImageView(device_,v,nullptr);swapchain_views_.clear();swapchain_images_.clear();if(swapchain_)vkDestroySwapchainKHR(device_,swapchain_,nullptr);swapchain_=VK_NULL_HANDLE;
}
void VulkanRenderer::shutdown(){if(instance_==VK_NULL_HANDLE)return;if(device_)vkDeviceWaitIdle(device_);destroy_swapchain();if(device_)vkDestroyDevice(device_,nullptr);if(surface_)vkDestroySurfaceKHR(instance_,surface_,nullptr);vkDestroyInstance(instance_,nullptr);device_=VK_NULL_HANDLE;surface_=VK_NULL_HANDLE;instance_=VK_NULL_HANDLE;initialized_=false;}
void VulkanRenderer::draw(){
 if(!device_||!swapchain_||dirty_){if(device_&&surface_&&dirty_)recreate_swapchain();return;}if(vkWaitForFences(device_,1,&in_flight_,VK_TRUE,1000000)!=VK_SUCCESS)return;uint32_t image=0;VkResult ar=vkAcquireNextImageKHR(device_,swapchain_,1000000,image_available_,VK_NULL_HANDLE,&image);if(ar==VK_ERROR_OUT_OF_DATE_KHR||ar==VK_SUBOPTIMAL_KHR){dirty_=true;return;}if(ar!=VK_SUCCESS)return;time_+=.008f;update_camera();vkResetFences(device_,1,&in_flight_);vkResetCommandBuffer(command_buffer_,0);VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};if(vkBeginCommandBuffer(command_buffer_,&bi)!=VK_SUCCESS)return;
 VkClearValue sd{};sd.depthStencil={1,0};VkRenderPassBeginInfo srp{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};srp.renderPass=shadow_render_pass_;srp.framebuffer=shadow_framebuffer_;srp.renderArea={{0,0},{1024,1024}};srp.clearValueCount=1;srp.pClearValues=&sd;vkCmdBeginRenderPass(command_buffer_,&srp,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindPipeline(command_buffer_,VK_PIPELINE_BIND_POINT_GRAPHICS,shadow_pipeline_);vkCmdBindDescriptorSets(command_buffer_,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline_layout_,0,1,&camera_set_,0,nullptr);uint32_t mode=1;vkCmdPushConstants(command_buffer_,pipeline_layout_,VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,4,&mode);VkDeviceSize off=0;vkCmdBindVertexBuffers(command_buffer_,0,1,&vertex_buffer_,&off);vkCmdBindIndexBuffer(command_buffer_,index_buffer_,0,VK_INDEX_TYPE_UINT16);vkCmdDrawIndexed(command_buffer_,index_count_,1,0,0,0);vkCmdEndRenderPass(command_buffer_);
 VkBufferMemoryBarrier fb{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER};fb.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;fb.dstAccessMask=VK_ACCESS_SHADER_READ_BIT|VK_ACCESS_SHADER_WRITE_BIT;fb.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;fb.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;fb.buffer=cluster_buffer_;fb.size=VK_WHOLE_SIZE;vkCmdFillBuffer(command_buffer_,cluster_buffer_,0,VK_WHOLE_SIZE,0);vkCmdPipelineBarrier(command_buffer_,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,0,0,nullptr,1,&fb,0,nullptr);
 VkDescriptorSet sets[]={camera_set_,lighting_set_};vkCmdBindPipeline(command_buffer_,VK_PIPELINE_BIND_POINT_COMPUTE,compute_pipeline_);vkCmdBindDescriptorSets(command_buffer_,VK_PIPELINE_BIND_POINT_COMPUTE,pipeline_layout_,0,2,sets,0,nullptr);vkCmdDispatch(command_buffer_,16*9*24,1,1);VkBufferMemoryBarrier cb{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER};cb.srcAccessMask=VK_ACCESS_SHADER_WRITE_BIT;cb.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;cb.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;cb.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;cb.buffer=cluster_buffer_;cb.size=VK_WHOLE_SIZE;vkCmdPipelineBarrier(command_buffer_,VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,nullptr,1,&cb,0,nullptr);
 VkClearValue cv{};cv.color={{.035f,.075f,.14f,1}};VkClearValue dv{};dv.depthStencil={1,0};VkClearValue cl[]={cv,dv};VkRenderPassBeginInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};rp.renderPass=render_pass_;rp.framebuffer=framebuffers_[image];rp.renderArea={{0,0},extent_};rp.clearValueCount=2;rp.pClearValues=cl;vkCmdBeginRenderPass(command_buffer_,&rp,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindVertexBuffers(command_buffer_,0,1,&vertex_buffer_,&off);vkCmdBindIndexBuffer(command_buffer_,index_buffer_,0,VK_INDEX_TYPE_UINT16);vkCmdBindPipeline(command_buffer_,VK_PIPELINE_BIND_POINT_GRAPHICS,sky_pipeline_);vkCmdBindDescriptorSets(command_buffer_,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline_layout_,0,2,sets,0,nullptr);mode=2;vkCmdPushConstants(command_buffer_,pipeline_layout_,VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,4,&mode);vkCmdDrawIndexed(command_buffer_,36,1,0,0,0);vkCmdBindPipeline(command_buffer_,VK_PIPELINE_BIND_POINT_GRAPHICS,graphics_pipeline_);mode=0;vkCmdPushConstants(command_buffer_,pipeline_layout_,VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,4,&mode);vkCmdDrawIndexed(command_buffer_,index_count_,1,0,0,0);vkCmdEndRenderPass(command_buffer_);
 if(vkEndCommandBuffer(command_buffer_)!=VK_SUCCESS)return;VkPipelineStageFlags wait=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.waitSemaphoreCount=1;si.pWaitSemaphores=&image_available_;si.pWaitDstStageMask=&wait;si.commandBufferCount=1;si.pCommandBuffers=&command_buffer_;si.signalSemaphoreCount=1;si.pSignalSemaphores=&render_finished_;if(vkQueueSubmit(graphics_queue_,1,&si,in_flight_)!=VK_SUCCESS)return;VkPresentInfoKHR pi{VK_STRUCTURE_TYPE_PRESENT_INFO_KHR};pi.waitSemaphoreCount=1;pi.pWaitSemaphores=&render_finished_;pi.swapchainCount=1;pi.pSwapchains=&swapchain_;pi.pImageIndices=&image;VkResult pr=vkQueuePresentKHR(graphics_queue_,&pi);if(pr==VK_ERROR_OUT_OF_DATE_KHR||pr==VK_SUBOPTIMAL_KHR)dirty_=true;
}
}}
}